# -*- coding: utf-8 -*-
"""hands_on.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1952alAN5e5pD6JfodHI-7VzVQEn1Euc6
"""

# GPU
!nvidia-smi

!git clone https://github.com/ultralytics/yolov5.git



# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!pip install -r requirements.txt

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="DDCKAczcbafR3Gkr2GSe")
project = rf.workspace("new-workspace-onq0e").project("deer-8swm3")
version = project.version(1)
dataset = version.download("yolov8-obb")

!python train.py --img 640 --batch 3 --epochs 2 --data /content/yolov5/Deer-1/data.yaml --weights yolov5m.pt

!python detect.py --weights /content/yolov5/runs/train/exp2/weights/best.pt --img 640 --source /content/yolov5/test.jpeg